#!/bin/bash
set -e

# Function to read version from package.json
get_version() {
  if [ -f "app/package.json" ]; then
    grep '"version":' app/package.json | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g'
  else
    echo "NONE"
  fi
}

VERSION=$(get_version)
if [[ "$VERSION" == "NONE" ]]; then
    echo "app/package.json not found. Please make sure you run ./scripts/release.sh from the root project dir"
    echo .
    exit 1
fi

TAG="zmNg-$VERSION"

echo "==================================================="
echo "   ZoneMinder Next Gen (zmNg) Release Script"
echo "==================================================="
echo "Detected Version: $VERSION"
echo "Target Tag:       $TAG"
echo "==================================================="
echo ""

# Check for uncommitted changes
if [[ -n $(git status --porcelain) ]]; then
    echo "❌ Error: You have uncommitted changes in your working directory."
    echo ""
    echo "Please commit or stash your changes before creating a release:"
    echo ""
    git status --short
    echo ""
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Check if branch has an upstream
if ! git rev-parse --abbrev-ref @{u} >/dev/null 2>&1; then
    echo "❌ Error: Current branch '$CURRENT_BRANCH' has no upstream branch."
    echo ""
    echo "Please push your branch first:"
    echo "  git push -u origin $CURRENT_BRANCH"
    echo ""
    exit 1
fi

# Check for unpushed commits
UNPUSHED=$(git rev-list @{u}..HEAD --count)
if [[ "$UNPUSHED" -gt 0 ]]; then
    echo "❌ Error: You have $UNPUSHED unpushed commit(s) on branch '$CURRENT_BRANCH'."
    echo ""
    echo "Please push your commits before creating a release:"
    echo "  git push origin $CURRENT_BRANCH"
    echo ""
    exit 1
fi

echo "✅ Working directory is clean"
echo "✅ All commits are pushed to origin"
echo ""
echo "This script will:"
echo "1. Create a local git tag '$TAG'"
echo "2. Push the tag to 'origin'"
echo "3. Trigger GitHub Actions to build, generate changelog, and create release"
echo ""
echo "Note: CHANGELOG.md will be generated by GitHub Actions using github_changelog_generator"
echo ""
read -p "Are you sure you want to proceed? (y/N) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Release cancelled."
    exit 1
fi

# Check if tag exists locally or remotely
TAG_EXISTS_LOCALLY=false
TAG_EXISTS_REMOTELY=false
MOVE_TAG=false

if git rev-parse "$TAG" >/dev/null 2>&1; then
    TAG_EXISTS_LOCALLY=true
fi

if git ls-remote --exit-code --tags origin "$TAG" >/dev/null 2>&1; then
    TAG_EXISTS_REMOTELY=true
fi

if [ "$TAG_EXISTS_LOCALLY" = true ] || [ "$TAG_EXISTS_REMOTELY" = true ]; then
    echo ""
    echo "⚠️  Tag '$TAG' already exists!"
    if [ "$TAG_EXISTS_LOCALLY" = true ]; then
        echo "   - Found locally"
    fi
    if [ "$TAG_EXISTS_REMOTELY" = true ]; then
        echo "   - Found on remote"
    fi
    echo ""
    echo "This will:"
    echo "1. Delete the existing tag (local and remote)"
    echo "2. Create a new tag '$TAG' at the current commit"
    echo "3. Force push the tag to trigger a new release build"
    echo ""
    read -p "Do you want to move the tag to the current commit? (y/N) " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Release cancelled."
        exit 1
    fi
    MOVE_TAG=true

    # Remove local tag
    if [ "$TAG_EXISTS_LOCALLY" = true ]; then
        echo "Deleting local tag $TAG..."
        git tag -d "$TAG"
    fi
fi

# Generate changelog locally using bundler
if [ -f "Gemfile" ] && command -v bundle &> /dev/null; then
    echo ""
    echo "📋 Generating CHANGELOG.md locally..."
    if CHANGELOG_GITHUB_TOKEN=$(gh auth token 2>/dev/null) bundle exec github_changelog_generator --future-release "$TAG"; then
        # Check if CHANGELOG.md was modified or is new
        if [[ -n $(git diff --name-only CHANGELOG.md 2>/dev/null) ]] || [[ -n $(git ls-files --others --exclude-standard CHANGELOG.md 2>/dev/null) ]]; then
            echo "📝 CHANGELOG.md updated, committing..."
            git add CHANGELOG.md
            git commit -m "chore: update CHANGELOG.md for $TAG"
            git push origin "$CURRENT_BRANCH"
            echo "✅ CHANGELOG.md committed and pushed"
        else
            echo "ℹ️  CHANGELOG.md unchanged"
        fi
    else
        echo "⚠️  Local changelog generation failed (this is OK - GitHub Actions will handle it)"
    fi
else
    echo ""
    echo "ℹ️  Gemfile or bundler not found"
    echo "   Run: bundle install"
    echo "   The changelog will be generated by GitHub Actions when the release is created"
fi

if [ "$MOVE_TAG" = true ]; then
    # Delete remote tag if it exists
    if [ "$TAG_EXISTS_REMOTELY" = true ]; then
        echo "Deleting remote tag $TAG..."
        git push origin --delete "$TAG" 2>/dev/null || true
    fi

    echo "Creating new tag $TAG at current commit..."
    git tag "$TAG"

    echo "Force pushing tag to origin..."
    git push origin "$TAG" --force
else
    echo "Creating tag $TAG..."
    git tag "$TAG"

    echo "Pushing tag to origin..."
    git push origin "$TAG"
fi

echo ""
echo "✅ Release triggered! Check GitHub Actions for progress."
echo "   https://github.com/pliablepixels/zmNg/actions"
echo ""
echo "The create-release workflow will:"
echo "  - Generate release notes with changelog"
echo "  - Create the GitHub Release"
echo "  - Build workflows will attach platform binaries"
